<a href="https://colab.research.google.com/github/Satyaki9207/Analytics_vidhya_hackathon_APR_2022/blob/master/00_introduction_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# craeting a scalar
a1=tf.constant(89)
a1

<tf.Tensor: shape=(), dtype=int32, numpy=89>

In [ ]:
# Number of dimensions of a tensor
a1.ndim

0

In [ ]:
vec=tf.constant([10,-10],dtype=tf.float16)
vec.ndim

1

### Creating tensors with `tf.Variable`

In [ ]:
t1=tf.Variable([10,7])
t2=tf.constant([10,7])

In [ ]:
t1[0].assign(-5)
t1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-5,  7], dtype=int32)>

In [ ]:
# Tf.constant class has no method assign and hence values are immutable

In [19]:
# Create random tensors with tf
tf.random.normal((2,3),mean=3.5,stddev=0.85,seed=42)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3.261341 , 3.3829107, 2.9251199],
       [3.5208933, 2.7404532, 2.7957978]], dtype=float32)>

In [20]:
# Shuffling a tensor
t1=tf.random.normal((5,4),mean=3.5,stddev=0.85,seed=42)
tf.random.shuffle(t1)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[3.6938424, 2.9935222, 3.4436815, 3.9829595],
       [3.1391554, 4.5635934, 3.678839 , 3.052738 ],
       [2.417154 , 3.8381925, 3.398679 , 2.542871 ],
       [3.9201753, 2.6774359, 3.3955748, 4.019311 ],
       [3.4876897, 5.1522613, 2.999082 , 4.4829655]], dtype=float32)>

In [24]:
# Creating arrays similar to numpy
tf.ones([3,3],dtype=tf.float16)

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)>

In [25]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>